### ISSUE TITLE
InfinitePaddedImage doesn't support loading of Dask Arrays

### ISSUE THREAD

**Issue by KristinaUlicna** [quantumjot/cellx#42]
In `cellx.tools.image` the `InfinitePaddedImage` requires `np.ndarray` -> therefore doesn't support loading of `dask_arrays` -> incompatible for use with `DaskOctopusLiteLoader` from this repo: [https://github.com/lowe-lab-ucl/octopuslite-reader](octopuslite-reader)

https://github.com/quantumjot/cellx/blob/56a22099beeba59401d6882b6d6b0010718c0376/cellx/tools/image.py#L42

**Comment by nthndy** [comment]
I ran into a similar issue with btrack and changed the functionality so that it would accept `dask_arrays` but in doing so realised that dasks' strengths seem to be when you actually want to view the image rather than iteratively load and process an image. I have ended up using the `DaskOctopusLiteLoader` to load file names and parse that to a generator function that is much quicker than using dask and doing `.compute()` every iteration.

**Comment by quantumjot** [comment]
I think I agree with Nathan here - this function doesn't need to directly support Dask arrays

**Comment by quantumjot** [comment]
I'm going to close this issue - feel free to reopen if you feel strongly about it!
